### ISSUE TITLE
Exception while Changing Orientation

### ISSUE THREAD

**Issue by mynote** [InQBarna/TableFixHeaders#71]
Hello,

ive a little problem. My Table is working great on a Tablet in Landscape mode. But after changing to a Phone with Potrait mode im getting an exception and the app crashes. Doesnt matter if ive the activity in landscape mode.

Here's my code. Any idea whats going wrong?

    public class MyActivity extends FragmentActivity {

     /** truncated alot **/

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
    }

     @Override
      protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_cash);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);

        tableProductsAdapter = new TableProductsAdapter(this);

        tableFixHeaders = (TableFixHeaders) findViewById(R.id.tableCashProducts);
        tableFixHeaders.setAdapter(tableProductsAdapter);

        tableProductsAdapter.registerDataSetObserver(new DataSetObserver() {
            @Override
            public void onChanged() {
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        tableFixHeaders.scrollTo(0, tableProductsAdapter.getRowCount());
                    }
                }, 0);
            }
        });
    }

    public void addProductOrder(ProductOrder productOrder) {
        tableProductsAdapter.addItem(productOrder);
        txtEndSum.setText(tableProductsAdapter.getProductSum() + " EUR");
    }

and the adapter...

     class TableProductsAdapter extends BaseTableAdapter {

        private List<ProductOrder> list;

        private LayoutInflater layoutInflater;

        private final String headers[] = {
                "Menge",
                "Preis",
                "Artikel / EAN",
                "Gesamtpreis"
        };

        private final int[] widths = {
                80,
                80,
                300,
                80
        };

        private final float density;

        private final static int WIDTH_DIP = 110;
        private final static int HEIGHT_DIP = 32;
        int width = 0, height = 0;

        public TableProductsAdapter(Context c) {
            list = new ArrayList<>();
            density = getResources().getDisplayMetrics().density;

            Resources r = getResources();

            width = Math.round(TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, WIDTH_DIP, r.getDisplayMetrics()));
            height = Math.round(TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, HEIGHT_DIP, r.getDisplayMetrics()));

            layoutInflater = LayoutInflater.from(c);
        }

        @Override
        public int getRowCount() {
            return list != null ? list.size() : 0;
        }

        @Override
        public int getColumnCount() {
            return headers.length - 1;
        }

        public void addItem(ProductOrder productOrder) {
            list.add(productOrder);
            notifyDataSetChanged();
        }

        public String getProductSum() {
            double currentSum = 0;
            for (ProductOrder productOrder : list) {
                currentSum += productOrder.getAmount() * productOrder.getProduct().getPrice();
            }
            return MathUtil.formatDoubleTwoDigits(currentSum);
        }

        @Override
        public View getView(int row, int column, View convertView, ViewGroup parent) {
            final View view;
            switch (getItemViewType(row, column)) {
                case 0:
                    view = getHeader(row, column, convertView, parent);
                    break;
                case 1:
                    view = getBody(row, column, convertView, parent);
                    break;
                default:
                    throw new RuntimeException("no viewtype");
            }
            return view;

        }

        private View getHeader(int row, int column, View convertView, ViewGroup parent) {
            if (convertView == null) {
                convertView = layoutInflater.inflate(R.layout.item_table_header, parent, false);
            }
            ((TextView) convertView.findViewById(android.R.id.text1)).setText(headers[column + 1]);
            return convertView;
        }

        private View getBody(final int row, int column, View convertView, ViewGroup parent) {
            if (convertView == null) {
                convertView = layoutInflater.inflate(R.layout.item_table, parent, false);
            }

            convertView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Log.e(TAG, "Clicked on row=" + row);
                }
            });

            convertView.setBackgroundResource(row % 2 == 0 ? R.drawable.bg_table_color1 : R.drawable.bg_table_color2);
            ProductOrder productOrder = list.get(row);
            switch (column) {
                case -1:
                    ((TextView) convertView.findViewById(android.R.id.text1)).setText(productOrder.getAmount() + "");
                    break;
                case 0:
                    ((TextView) convertView.findViewById(android.R.id.text1)).setText(productOrder.getProduct().getPrice() + " EUR");
                    break;
                case 1:
                    ((TextView) convertView.findViewById(android.R.id.text1)).setText(productOrder.getProduct().getName());
                    break;
                case 2:
                    ((TextView) convertView.findViewById(android.R.id.text1)).setText(productOrder.getAmount() * productOrder.getProduct().getPrice() + " EUR");
                    break;
                default:
            }
            return convertView;
        }

        @Override
        public int getWidth(int column) {
            return Math.round(widths[column + 1] * density);
        }

        @Override
        public int getHeight(int row) {

            final int height;
            if (row == -1) {
                height = 48;
            } else {
                height = 45;
            }
            return Math.round(height * density);
        }

        @Override
        public int getViewTypeCount() {
            return 2;
        }

        @Override
        public int getItemViewType(int row, int column) {
            final int itemViewType;
            if (row == -1) {
                itemViewType = 0;
            } else {
                itemViewType = 1;
            }
            return itemViewType;
        }
    }

this is the exception im getting on a phone.

 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1   at com.inqbarna.tablefixheaders.TableFixHeaders.adjustFirstCellsAndScroll(TableFixHeaders.java:647)
            at com.inqbarna.tablefixheaders.TableFixHeaders.adjustFirstCellsAndScroll(TableFixHeaders.java:638)
            at com.inqbarna.tablefixheaders.TableFixHeaders.onLayout(TableFixHeaders.java:577)

**Comment by BraisGabin** [comment]
The line 647 can't report this error. You changed something in the code, right?

Are you preventing to recreate the view after a rotation? This can be a problem, I didn't test this view in that circumstances.
