### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by HelloDearWorld** [InQBarna/TableFixHeaders#97]
java.lang.NullPointerException: Attempt to read from null array
                                                                                        at com.inqbarna.tablefixheaders.TableFixHeaders.computeHorizontalScrollOffset(TableFixHeaders.java:354)
                                                                                        at android.view.View.onDrawScrollBars(View.java:13204)
                                                                                        at android.view.View.draw(View.java:15609)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:14483)
                                                                                        at android.view.View.getDisplayList(View.java:14512)
                                                                                        at android.view.View.draw(View.java:15303)
                                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
                                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:14475)
                                                                                        at android.view.View.getDisplayList(View.java:14512)
                                                                                        at android.view.View.draw(View.java:15303)
                                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
                                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:14475)
                                                                                        at android.view.View.getDisplayList(View.java:14512)
                                                                                        at android.view.View.draw(View.java:15303)
                                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
                                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:14475)
                                                                                        at android.view.View.getDisplayList(View.java:14512)
                                                                                        at android.view.View.draw(View.java:15303)
                                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
                                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:14475)
                                                                                        at android.view.View.getDisplayList(View.java:14512)
                                                                                        at android.view.View.draw(View.java:15303)
                                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
                                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2816)
                                                                                        at android.view.View.draw(View.java:15606)
                                                                                        at android.widget.FrameLayout.draw(FrameLayout.java:658)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2795)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:14483)
                                                                                        at android.view.View.getDisplayList(View.java:14512)
                                                                                        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:279)
                                                                                        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:285)
                                                                                        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:335)
                                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3048)
                                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2857)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2468)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1329)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6780)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:818)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:621)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:584)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:804)
                                                                                        at android.os.Handler.handleCallback(Handler.java:815)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                        at android.os.Looper.loop(Looper.java:194)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5691)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by cyciopes** [comment]
@HelloDearWorld  hava you fixed this? I also have this issue.

**Comment by BraisGabin** [comment]
I can't help with this without a context or a code to reproduce it.

**Comment by asyrafduyshart** [comment]
I have the same issue here, have problem with widths, cannot get array reference
Somebody please help

**Comment by clbemre** [comment]
I have the same issue, please help ?
Tablefixheader inside activity --> NO ERROR WORK GREAT
BUT ????? 
Tablefixheader inside fragment --> ERROR WORK BAD

at error Table Fix Headers.sum Array(Table Fix Headers.java:615)
com.inqbarna.tablefixheaders.TableFixHeaders.computeHorizontalScrollOffset(TableFixHeaders.java:354)

Please help ?
